### ISSUE TITLE
Init container not building due to Sitecore.Cli target framework update

### ISSUE THREAD

**Issue by MiguelMinoldo** [Sitecore/Sitecore.Demo.Edge#403]
As the latest Sitecore.Cli packages is targetting the .NET Framework 6.0: https://sitecore.myget.org/feed/sc-packages/package/nuget/sitecore.cli/5.0.16 , and the project (Sitecore.Demo.Init.csproj) is based on netcoreapp3.1, the build is likely to fail while trying to install the latest Sitecore.Cli package: "Sitecore.cli 5.0.16 is not compatible with netcoreapp3.1.
I workaround it by specifying the version in the init Dockerfile.
<img width="575" alt="image" src="https://user-images.githubusercontent.com/14338387/174832417-afff2d07-fcfe-49ba-b4a7-58a5ca1f7f97.png">

**Comment by adoprog** [comment]
Thanks, it was updated in https://github.com/Sitecore/Sitecore.Demo.Edge/pull/398
