### ISSUE TITLE
Initial setup scripts fail

### ISSUE THREAD

**Issue by blepam** [Sitecore/Sitecore.Demo.Edge#528]
I just checked out the repo cleanly. Latest main branch. I made absolutely no customizations at all.

I ran through the following steps:

1. `.\init.ps1 -AdminPassword b -LicenseXmlPath (Resolve-Path 'C:\Sitecore\license\license.xml').Path -InitEnv`
2. .\up.ps1`

I was unable to login. I spoke to @jflheureux and he told me to check the mssql-init container. I saw this error:
![image](https://github.com/Sitecore/Sitecore.Demo.Edge/assets/133886699/8cc9bca9-177e-441e-8ded-641fb53e186b)

I went back and removed all the `-TrustServerCertificate` flags from the setup scripts, and then everything worked fine. 

```
OS: Windows 10 22H2 19045.3324
Docker Engine: v24.0.5
Docker Desktop: v4.22.1
Compose Version: 2
```

-Ben

**Comment by adoprog** [comment]
Is it possible that you have an old 'sxp/sitecore-xm1-mssql-init' base image cached that does not have -TrustServerCertificate support yet?

**Comment by blepam** [comment]
Yup, I think that was it. I went back and cleaned up any images with `mssql-init` in the name and that seemed to do it.

Thanks!
